---
postgres:
  hosts:
    node001:
      ansible_host: MY1
      ansible_ssh_user: ansible
    node002:
      ansible_host: MY2
      ansible_ssh_user: ansible
    node003:
      ansible_host: MY3
      ansible_ssh_user: ansible
